@startuml
skinparam style strictuml
skinparam ArrowThickness 2
hide empty members
title Modèle du domaine (adapté au Jeu de dés du Ch. 1 de Larman)

class Joueur {
  nom : String
  nbParties : int
  nbPartiesGagnées : int
}

class De {
  valeur : int
}

class JeuDeDes {
  d1 : De
  d2 : De
  d3 : De
}

// associations
Joueur "1" -down- "1" JeuDeDes : joue
JeuDeDes "1" -up- "3" De : inclut
@enduml
